[hotreload]
  suffixes = [".go"]
  ignore = []

[app]
  #app 名称
  name = "xggame"
  #app url
  url  = "http://localhost"
  #app 文档地址
  doc = "./apidoc"
  addr = ":80"
  #单元测试调试信息
  debug = false

  [app.logger]
    level = "INFO"
    name = "application"

#数据库驱动
[database]
    dirver = "mysql"

[mysql]
   databaseName ="xggame"
   databaseUserName ="sc4599"
   databasePassword ="qwert12345"
   databaseHost ="192.168.0.210:3306"

[mongodb]
  connect = "mongodb://root:123456@127.0.0.1:27017/admin"

[sqlite]
  connect = "/tmp/gorm.db"

#reids
[redis]
  Addr = "192.168.0.210:6379"
  Password = "qwert12345"
  DB = "10"

[neo4j]
    connect = "http://10.10.43.111:7474/db/data"

[test]
    #测试登陆用户名
    LoginUserName = "you_test_user_name"
    #测试用户名
    LoginName = "you_test_name"
    #测试用户密码
    LoginPwd = "you_test_user_password"
    #测试数据库驱动
    DataBaseDriver = "sqlite3"
    #测试数据库
    DataBaseConnect = "/tmp/gorm.db"
[wsip]
    # websocket 连接地址
    Address = "http://192.168.0.210:7777/ws"