// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 命令标识
type Cmd int32

const (
	// 系统命令
	Cmd_Invalid      Cmd = 0
	Cmd_Login        Cmd = 10001
	Cmd_Login2       Cmd = 10001
	Cmd_Create       Cmd = 10002
	Cmd_Join         Cmd = 10003
	Cmd_UpdateStatus Cmd = 10100
)

var Cmd_name = map[int32]string{
	0:     "Invalid",
	10001: "Login",
	// Duplicate value: 10001: "Login2",
	10002: "Create",
	10003: "Join",
	10100: "UpdateStatus",
}

var Cmd_value = map[string]int32{
	"Invalid":      0,
	"Login":        10001,
	"Login2":       10001,
	"Create":       10002,
	"Join":         10003,
	"UpdateStatus": 10100,
}

func (x Cmd) String() string {
	return proto.EnumName(Cmd_name, int32(x))
}

func (Cmd) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

type App int32

const (
	App_None   App = 0
	App_System App = 1
	App_NiuNiu App = 2
	App_HuLuYu App = 3
)

var App_name = map[int32]string{
	0: "None",
	1: "System",
	2: "NiuNiu",
	3: "HuLuYu",
}

var App_value = map[string]int32{
	"None":   0,
	"System": 1,
	"NiuNiu": 2,
	"HuLuYu": 3,
}

func (x App) String() string {
	return proto.EnumName(App_name, int32(x))
}

func (App) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}

// 响应状态码
type RespCode int32

const (
	RespCode_FAILURE         RespCode = 0
	RespCode_SUCCESS         RespCode = 1
	RespCode_FAILURE_UNKNOWN RespCode = 2
	RespCode_FAILURE_SERVER  RespCode = 3
)

var RespCode_name = map[int32]string{
	0: "FAILURE",
	1: "SUCCESS",
	2: "FAILURE_UNKNOWN",
	3: "FAILURE_SERVER",
}

var RespCode_value = map[string]int32{
	"FAILURE":         0,
	"SUCCESS":         1,
	"FAILURE_UNKNOWN": 2,
	"FAILURE_SERVER":  3,
}

func (x RespCode) String() string {
	return proto.EnumName(RespCode_name, int32(x))
}

func (RespCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{2}
}

// 命令头
type MsgHead struct {
	AppId                App      `protobuf:"varint,1,opt,name=app_id,json=appId,proto3,enum=protocol.App" json:"app_id,omitempty"`
	CmdId                Cmd      `protobuf:"varint,2,opt,name=cmd_id,json=cmdId,proto3,enum=protocol.Cmd" json:"cmd_id,omitempty"`
	Body                 []byte   `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgHead) Reset()         { *m = MsgHead{} }
func (m *MsgHead) String() string { return proto.CompactTextString(m) }
func (*MsgHead) ProtoMessage()    {}
func (*MsgHead) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

func (m *MsgHead) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgHead.Unmarshal(m, b)
}
func (m *MsgHead) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgHead.Marshal(b, m, deterministic)
}
func (m *MsgHead) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgHead.Merge(m, src)
}
func (m *MsgHead) XXX_Size() int {
	return xxx_messageInfo_MsgHead.Size(m)
}
func (m *MsgHead) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgHead.DiscardUnknown(m)
}

var xxx_messageInfo_MsgHead proto.InternalMessageInfo

func (m *MsgHead) GetAppId() App {
	if m != nil {
		return m.AppId
	}
	return App_None
}

func (m *MsgHead) GetCmdId() Cmd {
	if m != nil {
		return m.CmdId
	}
	return Cmd_Invalid
}

func (m *MsgHead) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

// 响应头
type RespBodyHead struct {
	Code                 RespCode `protobuf:"varint,1,opt,name=code,proto3,enum=protocol.RespCode" json:"code,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespBodyHead) Reset()         { *m = RespBodyHead{} }
func (m *RespBodyHead) String() string { return proto.CompactTextString(m) }
func (*RespBodyHead) ProtoMessage()    {}
func (*RespBodyHead) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}

func (m *RespBodyHead) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespBodyHead.Unmarshal(m, b)
}
func (m *RespBodyHead) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespBodyHead.Marshal(b, m, deterministic)
}
func (m *RespBodyHead) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespBodyHead.Merge(m, src)
}
func (m *RespBodyHead) XXX_Size() int {
	return xxx_messageInfo_RespBodyHead.Size(m)
}
func (m *RespBodyHead) XXX_DiscardUnknown() {
	xxx_messageInfo_RespBodyHead.DiscardUnknown(m)
}

var xxx_messageInfo_RespBodyHead proto.InternalMessageInfo

func (m *RespBodyHead) GetCode() RespCode {
	if m != nil {
		return m.Code
	}
	return RespCode_FAILURE
}

func (m *RespBodyHead) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

// 登录游戏请求
type LoginReq struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{2}
}

func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (m *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(m, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

// 登录游戏响应
type LoginResp struct {
	Code                 RespCode `protobuf:"varint,1,opt,name=code,proto3,enum=protocol.RespCode" json:"code,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResp) Reset()         { *m = LoginResp{} }
func (m *LoginResp) String() string { return proto.CompactTextString(m) }
func (*LoginResp) ProtoMessage()    {}
func (*LoginResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{3}
}

func (m *LoginResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResp.Unmarshal(m, b)
}
func (m *LoginResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResp.Marshal(b, m, deterministic)
}
func (m *LoginResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResp.Merge(m, src)
}
func (m *LoginResp) XXX_Size() int {
	return xxx_messageInfo_LoginResp.Size(m)
}
func (m *LoginResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResp proto.InternalMessageInfo

func (m *LoginResp) GetCode() RespCode {
	if m != nil {
		return m.Code
	}
	return RespCode_FAILURE
}

func (m *LoginResp) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

// 创建房间请求
type CreateReq struct {
	Options              int64    `protobuf:"varint,1,opt,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateReq) Reset()         { *m = CreateReq{} }
func (m *CreateReq) String() string { return proto.CompactTextString(m) }
func (*CreateReq) ProtoMessage()    {}
func (*CreateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{4}
}

func (m *CreateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateReq.Unmarshal(m, b)
}
func (m *CreateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateReq.Marshal(b, m, deterministic)
}
func (m *CreateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateReq.Merge(m, src)
}
func (m *CreateReq) XXX_Size() int {
	return xxx_messageInfo_CreateReq.Size(m)
}
func (m *CreateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateReq proto.InternalMessageInfo

func (m *CreateReq) GetOptions() int64 {
	if m != nil {
		return m.Options
	}
	return 0
}

// 创建房间请求
type CreateResp struct {
	Code                 RespCode `protobuf:"varint,1,opt,name=code,proto3,enum=protocol.RespCode" json:"code,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	RoomNo               string   `protobuf:"bytes,3,opt,name=room_no,json=roomNo,proto3" json:"room_no,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResp) Reset()         { *m = CreateResp{} }
func (m *CreateResp) String() string { return proto.CompactTextString(m) }
func (*CreateResp) ProtoMessage()    {}
func (*CreateResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{5}
}

func (m *CreateResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResp.Unmarshal(m, b)
}
func (m *CreateResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResp.Marshal(b, m, deterministic)
}
func (m *CreateResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResp.Merge(m, src)
}
func (m *CreateResp) XXX_Size() int {
	return xxx_messageInfo_CreateResp.Size(m)
}
func (m *CreateResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResp proto.InternalMessageInfo

func (m *CreateResp) GetCode() RespCode {
	if m != nil {
		return m.Code
	}
	return RespCode_FAILURE
}

func (m *CreateResp) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *CreateResp) GetRoomNo() string {
	if m != nil {
		return m.RoomNo
	}
	return ""
}

func init() {
	proto.RegisterEnum("protocol.Cmd", Cmd_name, Cmd_value)
	proto.RegisterEnum("protocol.App", App_name, App_value)
	proto.RegisterEnum("protocol.RespCode", RespCode_name, RespCode_value)
	proto.RegisterType((*MsgHead)(nil), "protocol.MsgHead")
	proto.RegisterType((*RespBodyHead)(nil), "protocol.RespBodyHead")
	proto.RegisterType((*LoginReq)(nil), "protocol.LoginReq")
	proto.RegisterType((*LoginResp)(nil), "protocol.LoginResp")
	proto.RegisterType((*CreateReq)(nil), "protocol.CreateReq")
	proto.RegisterType((*CreateResp)(nil), "protocol.CreateResp")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206) }

var fileDescriptor_555bd8c177793206 = []byte{
	// 410 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x90, 0xd1, 0x8a, 0xd3, 0x40,
	0x14, 0x86, 0x37, 0x4d, 0x9b, 0x36, 0x67, 0xeb, 0x3a, 0x1e, 0x05, 0x8b, 0x57, 0x25, 0xa8, 0x2c,
	0xbd, 0xe8, 0xc5, 0xee, 0x13, 0xd4, 0x50, 0xd9, 0x68, 0x77, 0x84, 0x09, 0x55, 0xf4, 0xa6, 0x64,
	0x33, 0xc3, 0x12, 0xdc, 0xcc, 0x19, 0x93, 0x89, 0xd0, 0xc7, 0x50, 0x5f, 0xd5, 0x07, 0x90, 0x99,
	0x36, 0x08, 0x7b, 0xdb, 0xab, 0xfc, 0x7f, 0xe6, 0xe3, 0xff, 0xcf, 0x39, 0x30, 0x2d, 0xa9, 0xae,
	0x49, 0x2f, 0x4d, 0x43, 0x96, 0x70, 0xe2, 0x3f, 0x25, 0x3d, 0x24, 0x15, 0x8c, 0x6f, 0xdb, 0xfb,
	0x1b, 0x55, 0x48, 0x7c, 0x0d, 0x51, 0x61, 0xcc, 0xae, 0x92, 0xb3, 0x60, 0x1e, 0x5c, 0x5e, 0x5c,
	0x3d, 0x59, 0xf6, 0xd4, 0x72, 0x65, 0x8c, 0x18, 0x15, 0xc6, 0x64, 0x9e, 0x2a, 0x6b, 0xe9, 0xa8,
	0xc1, 0x63, 0x2a, 0xad, 0xa5, 0x18, 0x95, 0xb5, 0xcc, 0x24, 0x22, 0x0c, 0xef, 0x48, 0xee, 0x67,
	0xe1, 0x3c, 0xb8, 0x9c, 0x0a, 0xaf, 0x93, 0x0d, 0x4c, 0x85, 0x6a, 0xcd, 0x3b, 0x92, 0x7b, 0xdf,
	0xf7, 0x16, 0x86, 0x25, 0x49, 0x75, 0x6c, 0xc3, 0xff, 0x39, 0x8e, 0x4a, 0x49, 0x2a, 0xe1, 0xdf,
	0xf1, 0x05, 0x8c, 0x54, 0xd3, 0x50, 0xe3, 0x0b, 0x63, 0x71, 0x30, 0xc9, 0x1c, 0x26, 0x1b, 0xba,
	0xaf, 0xb4, 0x50, 0x3f, 0x1c, 0x61, 0xe9, 0xbb, 0xd2, 0x3e, 0x2a, 0x16, 0x07, 0x93, 0x64, 0x10,
	0x1f, 0x89, 0xd6, 0x9c, 0x58, 0xf6, 0x06, 0xe2, 0xb4, 0x51, 0x85, 0x55, 0xae, 0x6d, 0x06, 0x63,
	0x32, 0xb6, 0x22, 0xdd, 0xfa, 0xb4, 0x50, 0xf4, 0x36, 0x29, 0x01, 0x7a, 0xec, 0xd4, 0x4a, 0x7c,
	0x09, 0xe3, 0x86, 0xa8, 0xde, 0x69, 0xf2, 0x47, 0x8c, 0x45, 0xe4, 0x2c, 0xa7, 0xc5, 0x37, 0x08,
	0xd3, 0x5a, 0xe2, 0x39, 0x8c, 0x33, 0xfd, 0xb3, 0x78, 0xa8, 0x24, 0x3b, 0x43, 0x80, 0x91, 0x5f,
	0x95, 0xfd, 0xe2, 0x78, 0x0e, 0x91, 0xd7, 0x57, 0x47, 0x73, 0x98, 0x88, 0xfd, 0xe6, 0x18, 0xc3,
	0xf0, 0x03, 0x55, 0x9a, 0xfd, 0xe1, 0xf8, 0x0c, 0xa6, 0x5b, 0x23, 0x0b, 0xab, 0x72, 0x5b, 0xd8,
	0xae, 0x65, 0x7f, 0xf9, 0xab, 0x01, 0x0b, 0x16, 0xd7, 0x10, 0xae, 0x8c, 0xc1, 0x09, 0x0c, 0x39,
	0x69, 0xe5, 0x83, 0xa3, 0x7c, 0xdf, 0x5a, 0x55, 0xb3, 0xc0, 0x69, 0x5e, 0x75, 0xbc, 0xea, 0xd8,
	0xc0, 0xe9, 0x9b, 0x6e, 0xd3, 0x7d, 0xed, 0x58, 0xb8, 0xb8, 0x85, 0x49, 0xbf, 0x91, 0x9b, 0xea,
	0xfd, 0x2a, 0xdb, 0x6c, 0xc5, 0x9a, 0x9d, 0x39, 0x93, 0x6f, 0xd3, 0x74, 0x9d, 0xe7, 0x2c, 0xc0,
	0xe7, 0xf0, 0xf4, 0xf8, 0xb2, 0xdb, 0xf2, 0x8f, 0xfc, 0xd3, 0x17, 0xce, 0x06, 0x88, 0x70, 0xd1,
	0xff, 0xcc, 0xd7, 0xe2, 0xf3, 0x5a, 0xb0, 0xf0, 0x2e, 0xf2, 0x77, 0xba, 0xfe, 0x17, 0x00, 0x00,
	0xff, 0xff, 0xad, 0xda, 0x4d, 0xaa, 0xb2, 0x02, 0x00, 0x00,
}
